### ISSUE TITLE
library error

### ISSUE THREAD

**Issue by suprohub** [Twinklebear/oidn-rs#27]
`/home/hom/.cargo/bin/cargo check --message-format json --workspace --all-targets -Z unstable-options --keep-going
   Compiling oidn v2.2.2
error: failed to run custom build command for `oidn v2.2.2`
error: failed to run custom build command for `oidn v2.2.2`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `/home/hom/RustroverProjects/pio/target/debug/build/oidn-c895223cfa369538/build-script-build` (exit status: 101)
  --- stdout
  cargo:error=Please set OIDN_DIR=<path to OpenImageDenoise install root>
  --- stderr
  thread 'main' panicked at /home/hom/.cargo/registry/src/index.crates.io-6f17d22bba15001f/oidn-2.2.2/build.rs:12:13:
  Failed to find OpenImageDenoise
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
     1: core::panicking::panic_fmt
               at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
     2: build_script_build::main
     3: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`
but i install openimagedenoise lib on arch linux

**Comment by Twinklebear** [comment]
You'll still need to set `OIDN_DIR` to the path to the OIDN library for the build script to find it: https://github.com/Twinklebear/oidn-rs/blob/master/build.rs#L6-L9 , it doesn't check if the file exists in your system library headers. So if you installed it on your system, you'd have something like `/usr/local/` or something (the path without the `lib` prefix)

**Comment by suprohub** [comment]
its dont work

**Comment by suprohub** [comment]
i write export OIDN_DIR=/usr/local and i still get error

**Comment by suprohub** [comment]
i get error NotPresent

**Comment by Twinklebear** [comment]
`/usr/local/` is just an example, arch may have not installed it under that path. You should check where `libOpenImageDenoise` is located on your system

**Comment by suprohub** [comment]
its /lib, so in OIDN_DIR i put / ???

**Comment by suprohub** [comment]
uhm its works

**Comment by suprohub** [comment]
delete put lib in code, before send issue i try set /lib/

**Comment by suprohub** [comment]
oh no it comes back

**Comment by suprohub** [comment]
it compiles once and now still error

**Comment by Twinklebear** [comment]
With the same error? You need to have that environment variable set each time when building
